# SPDX-License-Identifier: MIT
"""Generate example-based documentation for ellipsoid_tree.

For every program in examples/, this script runs the built executable in a
scratch directory, captures its stdout and any figures it writes, copies the
figures to docs/img/, and emits docs/examples/<name>.md showing the program,
its output, and its figures ("show, don't tell").

The generated markdown is committed. CI re-runs this script with --check,
which fails if any committed page differs from what the code actually
produces — so the documentation cannot drift from the library (the C++
analogue of Python doctests). Figure image bytes are exempt from the check
(tiny floating-point differences across toolchains would make them flaky);
the figures are still regenerated and committed from the maintainer machine.

Usage:
    python3 docs/generate_examples.py [--build-dir build] [--check]
"""

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
EXAMPLES_DIR = REPO / "examples"
DOCS_DIR = REPO / "docs"
PAGES_DIR = DOCS_DIR / "examples"
IMG_DIR = DOCS_DIR / "img"

GALLERY_NAME = "intersections_gallery"


def split_intro(source: str):
    """Leading '//' comment block -> (title, intro_markdown, remaining_source)."""
    lines = source.splitlines()
    intro = []
    body_start = 0
    for i, line in enumerate(lines):
        if line.startswith("//"):
            intro.append(line[2:].lstrip())
        else:
            body_start = i
            break
    while body_start < len(lines) and lines[body_start].strip() == "":
        body_start += 1
    title = intro[0] if intro else "Example"
    intro_md = "\n".join(intro[1:]).strip()
    return title, intro_md, "\n".join(lines[body_start:])


def run_example(exe: Path, scratch: Path) -> tuple[str, list[Path]]:
    result = subprocess.run([str(exe)], cwd=scratch, capture_output=True, text=True, timeout=300)
    if result.returncode != 0:
        sys.exit(f"example {exe.name} failed:\n{result.stdout}\n{result.stderr}")
    figures = sorted(p for p in scratch.iterdir() if p.suffix in (".svg", ".png"))
    return result.stdout, figures


def gallery_table(stdout: str, name: str) -> str:
    """Build the pairwise table from '<panel> -> true/false' lines."""
    verdicts = {}
    order = []
    for line in stdout.splitlines():
        m = re.match(r"^(\w+)\s+->\s+(true|false)$", line.strip())
        if m:
            verdicts[m.group(1)] = m.group(2)
            base = re.sub(r"_(yes|no)$", "", m.group(1))
            if base not in order:
                order.append(base)

    rows = ["| pair | intersecting | disjoint |", "| --- | --- | --- |"]
    for base in order:
        cells = [f"`{base.replace('_', ' vs ', 1)}`"]
        for suffix in ("yes", "no"):
            panel = f"{base}_{suffix}"
            img = f"../img/{name}__{panel}.svg"
            cells.append(f'<img src="{img}" width="290"><br>`intersects -> {verdicts[panel]}`')
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join(rows)


def build_page(name: str, title: str, intro: str, body: str, stdout: str,
               figure_names: list[str]) -> str:
    parts = [f"# {title}", ""]
    if intro:
        parts += [intro, ""]
    if name == GALLERY_NAME:
        parts += [gallery_table(stdout, name), ""]
    parts += ["## Program", "", "```cpp", body.rstrip(), "```", ""]
    parts += ["## Output", "", "```text", stdout.rstrip(), "```", ""]
    if name != GALLERY_NAME and figure_names:
        parts += ["## Figures", ""]
        for fig in figure_names:
            parts += [f"![{fig}](../img/{name}__{fig})", ""]
    parts += ["---", "",
              "*This page is generated by `docs/generate_examples.py` from "
              f"[`examples/{name}.cpp`](../../examples/{name}.cpp); "
              "the output and figures above are produced by actually running it.*", ""]
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--build-dir", default="build")
    parser.add_argument("--check", action="store_true",
                        help="fail if regenerating changes any committed page")
    args = parser.parse_args()

    build_dir = (REPO / args.build_dir).resolve()
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    IMG_DIR.mkdir(parents=True, exist_ok=True)

    names = sorted(p.stem for p in EXAMPLES_DIR.glob("*.cpp"))
    index_lines = ["# ellipsoid_tree examples", "",
                   "Each page shows a complete program, its actual output, and the "
                   "figures it draws — all regenerated from the code by "
                   "`docs/generate_examples.py`.", ""]

    for name in names:
        exe = build_dir / "examples" / name
        if not exe.exists():
            sys.exit(f"missing executable {exe}; build with -DELLIPSOID_TREE_BUILD_EXAMPLES=ON first")
        source = (EXAMPLES_DIR / f"{name}.cpp").read_text()
        title, intro, body = split_intro(source)

        with tempfile.TemporaryDirectory() as tmp:
            scratch = Path(tmp)
            stdout, figures = run_example(exe, scratch)
            figure_names = []
            for fig in figures:
                target = IMG_DIR / f"{name}__{fig.name}"
                shutil.copyfile(fig, target)
                figure_names.append(fig.name)

        page = build_page(name, title, intro, body, stdout, figure_names)
        (PAGES_DIR / f"{name}.md").write_text(page)
        index_lines.append(f"- [{title}](examples/{name}.md)")
        print(f"generated docs/examples/{name}.md ({len(figure_names)} figures)")

    index_lines += [
        "",
        "## Python",
        "",
        "- [Non-overlapping ellipsoid batches (Jupyter notebook)]"
        "(../examples/python_batch_picking.ipynb) — the batch-picking example via the "
        "Python bindings; re-executed in CI (outputs not diffed) and rendered inline by GitHub.",
        "",
    ]
    (DOCS_DIR / "README.md").write_text("\n".join(index_lines))

    if args.check:
        diff = subprocess.run(
            ["git", "diff", "--exit-code", "--", "docs/README.md", "docs/examples"],
            cwd=REPO)
        if diff.returncode != 0:
            sys.exit("documentation is stale: regenerate with docs/generate_examples.py and commit")
        print("documentation is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
